-- Enhanced game list with categories and sample images
INSERT INTO games (game_name, category, image_url) VALUES
-- Video Games
('FIFA 23', 'Sports', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5p2s.png'),
('Call of Duty: Modern Warfare II', 'FPS', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5x74.png'),
('Minecraft', 'Sandbox', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4xci.png'),
('Grand Theft Auto V', 'Action-Adventure', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1nbw.png'),
('Fortnite', 'Battle Royale', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c2w.png'),
('Apex Legends', 'Battle Royale', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1p74.png'),
('Valorant', 'FPS', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3s.png'),
('League of Legends', 'MOBA', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c2u.png'),
('Dota 2', 'MOBA', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c2v.png'),
('Counter-Strike: Global Offensive', 'FPS', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c2x.png'),
('Overwatch 2', 'FPS', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5x7a.png'),
('Rainbow Six Siege', 'FPS', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c2y.png'),
('Rocket League', 'Sports', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c2z.png'),
('NBA 2K23', 'Sports', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5p2t.png'),
('PUBG: Battlegrounds', 'Battle Royale', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c31.png'),
('Among Us', 'Party', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c32.png'),
('Fall Guys', 'Party', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c33.png'),
('Warzone', 'Battle Royale', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c34.png'),
('Elden Ring', 'RPG', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c35.png'),
('God of War Ragnarök', 'Action-Adventure', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5x7b.png'),
('The Last of Us Part II', 'Action-Adventure', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c36.png'),
('Cyberpunk 2077', 'RPG', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c37.png'),
('Red Dead Redemption 2', 'Action-Adventure', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c38.png'),
('Genshin Impact', 'RPG', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c39.png'),
('Mobile Legends: Bang Bang', 'MOBA', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3a.png'),
('Clash of Clans', 'Strategy', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3b.png'),
('Clash Royale', 'Strategy', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3c.png'),
('Free Fire', 'Battle Royale', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3d.png'),
('Pokémon GO', 'AR', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3e.png'),
('Asphalt 9: Legends', 'Racing', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3f.png'),

-- Board Games
('Chess', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3g.png'),
('Checkers', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3h.png'),
('Scrabble', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3i.png'),
('Monopoly', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3j.png'),
('Ludo', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3k.png'),
('Draft', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3l.png'),
('Oware', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3m.png'),
('Mancala', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3n.png'),
('Catan', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3o.png'),
('Uno', 'Card Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3p.png'),
('Poker', 'Card Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3q.png'),
('Bridge', 'Card Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3r.png'),
('Jenga', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3t.png'),
('Risk', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3u.png'),
('Cards Against Humanity', 'Card Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3v.png'),

-- Traditional African Games
('Morabaraba', 'Traditional', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3w.png'),
('Diketo', 'Traditional', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3x.png'),
('Ntimo', 'Traditional', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3y.png'),
('Kgati', 'Traditional', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c3z.png'),
('Dibeke', 'Traditional', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c40.png'),
('Ampe', 'Traditional', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c41.png'),
('Ayo', 'Traditional', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c42.png'),
('Songo', 'Traditional', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c43.png'),

-- Mobile Games popular in Africa
('Subway Surfers', 'Mobile', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c44.png'),
('Temple Run 2', 'Mobile', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c45.png'),
('Candy Crush Saga', 'Puzzle', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c46.png'),
('8 Ball Pool', 'Sports', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c47.png'),
('Dream League Soccer', 'Sports', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c48.png'),
('PES Mobile', 'Sports', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c49.png'),
('Ludo King', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c4a.png'),
('Carrom Pool', 'Board Game', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4c4b.png');